// Mock Database
import { Priority, Task, TaskStatus } from "@/lib/definitions";

const tasks: {
  [TaskStatus.OPEN]: Task[];
  [TaskStatus.IN_PROGRESS]: Task[];
  [TaskStatus.CLOSED]: Task[];
} = {
  [TaskStatus.OPEN]: [
    {
      id: 1,
      name: "Implement responsive mobile layout",
      labels: ["UI Update", "Responsive Design"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-15T09:30:00.000Z",
      updated_at: "2023-11-15T09:30:00.000Z",
      priority: Priority.HIGH,
      assignee: "Jane Smith",
      description:
        "Make sure it looks pretty on screens of all sizes—even that tiny smartwatch no one really uses for browsing.",
    },
    {
      id: 2,
      name: "Migrate user authentication to OAuth 2.0",
      labels: ["Security", "Auth"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-18T14:20:00.000Z",
      updated_at: "2023-11-18T14:20:00.000Z",
      priority: Priority.URGENT,
      assignee: "Michael Johnson",
      description:
        "The only way to prove you’re human without actually solving a riddle or clicking traffic lights.",
    },
    {
      id: 3,
      name: "Implement customer feedback survey",
      labels: ["Customer Experience", "Metrics"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-20T11:45:00.000Z",
      updated_at: "2023-11-20T11:45:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Emily Davis",
      description:
        "Find out what our customers think, while secretly hoping they don’t ask for free coffee.",
    },
    {
      id: 4,
      name: "Add support for dark mode",
      labels: ["UI Update", "Accessibility"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-22T16:10:00.000Z",
      updated_at: "2023-11-22T16:10:00.000Z",
      priority: Priority.LOW,
      assignee: "David Lee",
      description:
        "For those late-night scrollers who like their screens as dark as their coffee.",
    },
    {
      id: 5,
      name: "Implement reporting dashboard",
      labels: ["Analytics", "Reporting"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-25T08:00:00.000Z",
      updated_at: "2023-11-25T08:00:00.000Z",
      priority: Priority.HIGH,
      assignee: "Sarah Kim",
      description:
        "Because nothing says ‘progress’ like a dashboard with 25 colorful pie charts.",
    },
    {
      id: 6,
      name: "Add A/B testing framework",
      labels: ["Experimentation", "Product"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-27T13:30:00.000Z",
      updated_at: "2023-11-27T13:30:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Alex Patel",
      description:
        "Help us decide if users prefer the blue button...or the slightly darker blue button.",
    },
    {
      id: 7,
      name: "Enhance search engine optimization",
      labels: ["SEO", "Marketing"],
      status: TaskStatus.OPEN,
      created_at: "2023-11-30T15:45:00.000Z",
      updated_at: "2023-11-30T15:45:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Samantha Flores",
      description:
        "Because we want our website to be the first thing you see—even when you’re looking for something else.",
    },
    {
      id: 8,
      name: "Implement email marketing campaigns",
      labels: ["Marketing", "Automation"],
      status: TaskStatus.OPEN,
      created_at: "2023-12-02T10:15:00.000Z",
      updated_at: "2023-12-02T10:15:00.000Z",
      priority: Priority.LOW,
      assignee: "John Doe",
      description:
        "Nothing says ‘we care’ like 17 promotional emails in a week. Time to automate that love!",
    },
    {
      id: 9,
      name: "Upgrade payment gateway integration",
      labels: ["Payments", "Compliance"],
      status: TaskStatus.OPEN,
      created_at: "2023-12-05T14:00:00.000Z",
      updated_at: "2023-12-05T14:00:00.000Z",
      priority: Priority.HIGH,
      assignee: "Jane Smith",
      description:
        "Because it’s time our payment gateway stopped acting like a picky bouncer on Friday night.",
    },
    {
      id: 10,
      name: "Enhance user onboarding experience",
      labels: ["Onboarding", "User Experience"],
      status: TaskStatus.OPEN,
      created_at: "2023-12-08T11:35:00.000Z",
      updated_at: "2023-12-08T11:35:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Michael Johnson",
      description:
        "Make our new users feel as welcome as a guest with fresh cookies and a name tag.",
    },
  ],
  [TaskStatus.IN_PROGRESS]: [
    {
      id: 11,
      name: "Refactor billing system",
      labels: ["Refactor", "Billing"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-11-10T08:00:00.000Z",
      updated_at: "2023-11-17T14:30:00.000Z",
      priority: Priority.HIGH,
      assignee: "Sarah Kim",
      description:
        "Because sometimes our code is as messy as a Monday morning desk.",
    },
    {
      id: 12,
      name: "Implement customer support chat",
      labels: ["Customer Experience", "Support"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-11-12T13:45:00.000Z",
      updated_at: "2023-11-19T10:15:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Alex Patel",
      description:
        "The closest thing to hiring a psychic—anticipating customer complaints before they start.",
    },
    {
      id: 13,
      name: "Optimize search algorithm",
      labels: ["Optimization", "Search"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-11-16T15:00:00.000Z",
      updated_at: "2023-11-21T18:30:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Samantha Flores",
      description:
        "Making sure users find what they’re looking for—even if they can’t spell it right.",
    },
    {
      id: 14,
      name: "Implement data visualization tools",
      labels: ["Analytics", "Visualization"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-11-23T09:20:00.000Z",
      updated_at: "2023-11-28T16:45:00.000Z",
      priority: Priority.HIGH,
      assignee: "John Doe",
      description:
        "Because nothing says ‘data-driven’ like charts with way too many colors.",
    },
    {
      id: 15,
      name: "Migrate to new CRM system",
      labels: ["CRM", "Migration"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-11-27T08:00:00.000Z",
      updated_at: "2023-12-03T14:10:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Jane Smith",
      description: "The grass is always greener...on the newer CRM system.",
    },
    {
      id: 16,
      name: "Implement export to CSV functionality",
      labels: ["Export", "Data"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-12-01T11:30:00.000Z",
      updated_at: "2023-12-06T15:20:00.000Z",
      priority: Priority.LOW,
      assignee: "Michael Johnson",
      description:
        "Because sometimes, all we want is a good old-fashioned spreadsheet.",
    },
    {
      id: 17,
      name: "Upgrade serverless infrastructure",
      labels: ["Infrastructure", "Scalability"],
      status: TaskStatus.IN_PROGRESS,
      created_at: "2023-12-04T07:45:00.000Z",
      updated_at: "2023-12-09T13:00:00.000Z",
      priority: Priority.HIGH,
      assignee: "Emily Davis",
      description:
        "To infinity and beyond! Scaling our system without lifting a server.",
    },
  ],
  [TaskStatus.CLOSED]: [
    {
      id: 18,
      name: "Implement user analytics dashboard",
      labels: ["Analytics", "Metrics"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-01T10:00:00.000Z",
      updated_at: "2023-11-08T17:45:00.000Z",
      priority: Priority.HIGH,
      assignee: "John Doe",
      description:
        "Because everyone loves a dashboard... until they have to maintain it.",
    },
    {
      id: 19,
      name: "Migrate to new CRM system",
      labels: ["CRM", "Migration"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-05T08:30:00.000Z",
      updated_at: "2023-11-14T13:20:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Jane Smith",
      description:
        "Finally saying goodbye to the CRM system that never loved us back.",
    },
    {
      id: 20,
      name: "Implement export to CSV functionality",
      labels: ["Export", "Data"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-09T14:00:00.000Z",
      updated_at: "2023-11-18T11:40:00.000Z",
      priority: Priority.LOW,
      assignee: "Michael Johnson",
      description: "Because data looks best when exported... and ignored.",
    },
    {
      id: 21,
      name: "Optimize product landing page",
      labels: ["Marketing", "UI"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-13T16:20:00.000Z",
      updated_at: "2023-11-22T09:55:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Sarah Kim",
      description:
        "Making sure our landing page is prettier than the competition’s cat memes.",
    },
    {
      id: 22,
      name: "Enhance user notification system",
      labels: ["Notifications", "UX"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-18T11:00:00.000Z",
      updated_at: "2023-11-26T14:30:00.000Z",
      priority: Priority.LOW,
      assignee: "Alex Patel",
      description:
        "Helping users stay informed—without overdoing it and becoming spam.",
    },
    {
      id: 23,
      name: "Improve site accessibility",
      labels: ["Accessibility", "Compliance"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-23T08:45:00.000Z",
      updated_at: "2023-12-01T17:20:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "Samantha Flores",
      description:
        "Because everyone should be able to enjoy our website... even on dial-up!",
    },
    {
      id: 24,
      name: "Integrate with third-party APIs",
      labels: ["Integration", "Partnerships"],
      status: TaskStatus.CLOSED,
      created_at: "2023-11-27T14:00:00.000Z",
      updated_at: "2023-12-04T11:10:00.000Z",
      priority: Priority.HIGH,
      assignee: "Emily Davis",
      description:
        "Because why reinvent the wheel when you can borrow someone else’s APIs?",
    },
    {
      id: 25,
      name: "Implement automated testing framework",
      labels: ["Testing", "CI/CD"],
      status: TaskStatus.CLOSED,
      created_at: "2023-12-02T10:00:00.000Z",
      updated_at: "2023-12-08T15:45:00.000Z",
      priority: Priority.MEDIUM,
      assignee: "David Lee",
      description:
        "Our attempt to catch bugs before they catch us by surprise on release day.",
    },
  ],
};

export const getTasks = (status: TaskStatus) => tasks[status];
